client: Fix compilation error by including a more specific header file.
The compilation error was:
[  5%] Building CXX object CMakeFiles/xtreemfs.dir/src/libxtreemfs/interrupt.cpp.o
In file included from /usr/include/boost/date_time/local_time/tz_database.hpp:14,
                 from /usr/include/boost/date_time/local_time/local_time.hpp:19,
                 from /usr/include/boost/date_time.hpp:15,
                 from /scratch/autotests/checkouts/xtreemfs_checkout-20120616T000001/cpp/src/libxtreemfs/interrupt.cpp:10:
/usr/include/boost/date_time/tz_db_base.hpp:161: error: declaration of ‘typedef class boost::date_time::dst_adjustment_offsets<typename time_zone_type::time_duration_type> boost::date_time::tz_db_base<time_zone_type, rule_type>::dst_adjustment_offsets’
/usr/include/boost/date_time/time_zone_base.hpp:76: error: changes meaning of ‘dst_adjustment_offsets’ from ‘class boost::date_time::dst_adjustment_offsets<typename time_zone_type::time_duration_type>’

http://lists.boost.org/boost-users/2009/01/43983.php contains the required fix for the boost library. However, we could work around the error by including a more specific header. This way, we don't have to require newer boost versions which contain the original fix.

git-svn-id: https://xtreemfs.googlecode.com/svn/trunk@3166 f8528748-c2c0-11dd-ba5c-d3b7c2b3b534