server: R/W Replication Stage: Do not always return EIO if fetching objects failed. Instead, take care of the values of the PBRPCException or return an IO_ERROR instead.
This fixes a problem where the client stopped to retry a write due to the following stack trace:

java.io.IOException: sending RPC failed: request timed out
  at org.xtreemfs.foundation.pbrpc.client.RPCResponse.get(RPCResponse.java:68)
  at org.xtreemfs.osd.rwre.RWReplicationStage$4.responseAvailable(RWReplicationStage.java:479)
  at org.xtreemfs.foundation.pbrpc.client.RPCResponse.requestFailed(RPCResponse.java:146)
  at org.xtreemfs.foundation.pbrpc.client.RPCNIOSocketClient.checkForTimers(RPCNIOSocketClient.java:720)
  at org.xtreemfs.foundation.pbrpc.client.RPCNIOSocketClient.run(RPCNIOSocketClient.java:261)

git-svn-id: https://xtreemfs.googlecode.com/svn/trunk@3141 f8528748-c2c0-11dd-ba5c-d3b7c2b3b534